stages:
  - build
  - push
  - deploy

variables:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ACCESS_KEY_ID: AKIAUNC467SMOH2XM5NF
  AWS_SECRET_ACCESS_KEY: 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

build:
  stage: build
  image: 
    name: registry.gitlab.com/telecomproject/cluster/telecomproject:latest
  services:
    - docker:19-dind
  before_script:
    - aws ecr create-repository --repository-name $CI_PROJECT_NAME --region $AWS_DEFAULT_REGION >> /dev/null || true
    - export DOCKER_REGISTRY=`aws ecr describe-repositories --repository-names $CI_PROJECT_NAME --query repositories[].repositoryUri --output text`
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -t $CI_PROJECT_NAME:latest .
    - docker image tag $CI_PROJECT_NAME:latest $DOCKER_REGISTRY/$CI_PROJECT_NAME:latest
    - docker image tag $CI_PROJECT_NAME:latest registry.gitlab.com/telecomproject/$CI_PROJECT_NAME/$CI_PROJECT_NAME:latest
    - docker image ls
    - docker push registry.gitlab.com/telecomproject/$CI_PROJECT_NAME/$CI_PROJECT_NAME:latest
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_NAME:latest