include:
  - project: 'telecomproject/resources'
    ref: $INCLUDE_BRANCH
    file: '/.gl-templates/microservices.gitlab-ci.yml'

test:
  extends: .test-go

#build:
#  needs:
#    - test

deploy:
  after_script:
    - kubectl get service frontend-external | awk '{print $4}'
