include:
  - project: 'telecomproject/resources'
    ref: $INCLUDE_BRANCH
    file: '/.gl-templates/microservices.gitlab-ci.yml'

variables:
  NAMESPACE: prod

test:
  extends: .test-go

#build:
#  needs:
#    - test
#

deploy:
  after_script:
    - kubectl get service frontend-external -n $NAMESPACE | awk '{print $4}'
