stages:
  - build
  - push
  - deploy

variables:
  CI_GROUP_NAME: telecomproject
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ACCESS_KEY_ID: AKIAUNC467SMOH2XM5NF
  AWS_SECRET_ACCESS_KEY: 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

build:
  stage: build
  image: 
    name: registry.gitlab.com/telecomproject/cluster/telecomproject:latest
  services:
    - docker:19-dind
  before_script:
    - aws ecr create-repository --repository-name $CI_GROUP_NAME --region $AWS_DEFAULT_REGION >> /dev/null || true
    - export DOCKER_REGISTRY=`aws ecr describe-repositories --repository-names telecomproject --query repositories[].repositoryUri --output text`
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -t $DOCKER_REGISTRY:$CI_PROJECT_NAME .
    - docker push $DOCKER_REGISTRY:$CI_PROJECT_NAME