apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: telecomproject
  region: eu-west-1


nodeGroups:
  - name: node-1
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 50 